- hosts: all
  become: yes
  tasks:
    - name: create the "vlad" user
      user: name=vlad append=yes state=present createhome=yes shell=/bin/bash

    - name: allow "vlad" to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'vlad ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the vlad user
      authorized_key: user=vlad key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
